sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - stable


# Install ALSA development libraries before compiling on Linux.
addons:
  apt:
    packages:
        - libasound2-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fc87a993d7683ec8b279
    on_success: change
    on_failure: always
    on_start: never

script:
  - cargo build
  - cargo doc
  - cargo test
# - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then (cargo bench); fi
